# identifiers for edge partitions
#EDGE_PARTITION_RETINA_TO_FILTER is unnecessary because \
#the input node has no mechanism to append to the key value anyway.
EDGE_PARTITION_FILTER_TO_PARTICLES = "filter_to_particles"
EDGE_PARTITION_PARTICLE_TO_PARTICLE = "particle_to_particle"
EDGE_PARTITION_MAIN_TO_FILTER = "main_to_filter"
EDGE_PARTITION_TARGET_POSITION = "target_output"

#force the raw retina input to have this keyspace
RETINA_BASE_KEY = 0x00000000

#append an identifier to the filtered events going to the particles
FILTER_BASE_KEY = 0x00100000

#append an identifier to the particle sending ROI position
MAIN_PARTICLE_ROI_KEY = 0x00200000

#append an identifier to the particle sending target position out
MAIN_PARTICLE_TARGET_KEY = 0x00300000

# PARTICLE_TO_PARTICLE base key is autogenerated because the key doesn't encode
# information

#used for incoming partition constraints and outgoing partition constraints of \
#the filters - only look at the Y value and FILTER_BASE_KEY!
FILTER_BASE_MASK = 0xFFFFFC00

#used to identify key-coded messages that are non-retina
MESSAGE_TYPE_MASK = 0xFFF00000


RETINA_X_SIZE = 304
RETINA_Y_SIZE = 240
RETINA_Y_BIT_SHIFT = 12
INITIAL_R = 30
PARTICLES = 60
MAX_BATCH_SIZE = 256

#used by old particle/aggregator system
EDGE_PARTITION_RE_SAMPLE = "Resample"
MAIN_PARTICLE_BASE_KEY = 0x01100000
RETINA_MASK = 0xFFF00000

MACHINE_STEPS = 400
US_PER_STEP = 100000
